GET http://localhost:3000/api

###

GET http://localhost:3000/api/profile

###

POST http://localhost:3000/api/profile/
Content-Type: application/json

{
    "name": "William Lee",
    "email": "william.lee@example.com",
    "password": "happy123",
    "city": "Phoenix",
    "gender": "Male",
    "gender_preference": "Female",
    "age": 35,
    "age_preference": { "min": 30, "max": 40 },
    "photo_url": "https://example.com/william-lee-avatar.jpg",
    "hobbies": ["Golf", "Traveling", "Movies"]
}

###

GET http://localhost:3000/api/profile/6535cf8a487a17c8eb3a2ac6

###

DELETE http://localhost:3000/api/profile/6535cf8a487a17c8eb3a2ac6



{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjUzNWNmOGE0ODdhMTdjOGViM2EyYWM2In0sImlhdCI6MTY5ODAyNTM1NX0.pdDNIhx2rk4pJOulgaaN2Xvr32Q7BE1OxvP_mLtUh4I"
}