GET http://localhost:3000/api

###

GET http://localhost:3000/api/profile

###

POST http://localhost:3000/api/profile/
Content-Type: application/json

{
    "name": "William Lee",
    "email": "william.lee@example.com",
    "password": "happy123",
    "city": "Phoenix",
    "gender": "Male",
    "gender_preference": "Female",
    "age": 35,
    "age_preference": { "min": 30, "max": 40 },
    "photo_url": "https://example.com/william-lee-avatar.jpg",
    "hobbies": ["Golf", "Traveling", "Movies"]
}

###

GET http://localhost:3000/api/profile/65350a1c77dc199c416a0dc7

###

DELETE http://localhost:3000/api/profile/65349ddbfd2d4281c094cca1