GET http://localhost:3000/api

###

GET http://localhost:3000/api/profile
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjUzNWNmOGE0ODdhMTdjOGViM2EyYWM2In0sImlhdCI6MTY5ODAyNTM1NX0.pdDNIhx2rk4pJOulgaaN2Xvr32Q7BE1OxvP_mLtUh4I

###

POST http://localhost:3000/api/profile/
Content-Type: application/json

{
    "name": "William Lee",
    "email": "william.lee@example.com",
    "password": "happy123",
    "city": "Phoenix",
    "gender": "Male",
    "gender_preference": "Female",
    "age": 35,
    "age_preference": { "min": 30, "max": 40 },
    "photo_url": "https://example.com/william-lee-avatar.jpg",
    "hobbies": ["Golf", "Traveling", "Movies"]
}

###
POST http://localhost:3000/api/auth/
Content-Type: application/json

{
    "email": "william.lee@example.com",
    "password": "happy123"
}

###

GET http://localhost:3000/api/profile/65364a7e8816411f9290a536
  x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjUzNWNmOGE0ODdhMTdjOGViM2EyYWM2In0sImlhdCI6MTY5ODAyNTM1NX0.pdDNIhx2rk4pJOulgaaN2Xvr32Q7BE1OxvP_mLtUh4I


###

DELETE http://localhost:3000/api/profile/65364b898816411f9290a544


